DROP TRIGGER IF EXISTS trg_agent_tombstone ON assistant.agents;
DROP FUNCTION IF EXISTS assistant.agent_tombstone();
DROP TABLE IF EXISTS assistant.agent_tombstones;
DROP TRIGGER IF EXISTS trg_agent_change_seq ON assistant.agents;
DROP FUNCTION IF EXISTS assistant.bump_agent_change_seq();
ALTER TABLE assistant.agents DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS assistant.agent_change_seq;
DROP TRIGGER IF EXISTS trg_folder_tombstone ON assistant.folders;
DROP FUNCTION IF EXISTS assistant.folder_tombstone();
DROP TABLE IF EXISTS assistant.folder_tombstones;
DROP TRIGGER IF EXISTS trg_folder_change_seq ON assistant.folders;
DROP FUNCTION IF EXISTS assistant.bump_folder_change_seq();
ALTER TABLE assistant.folders DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS assistant.folder_change_seq;
DROP TRIGGER IF EXISTS trg_msg_bump_conv ON assistant.messages;
DROP FUNCTION IF EXISTS assistant.msg_bump_conv();
DROP TRIGGER IF EXISTS trg_conv_tombstone ON assistant.conversations;
DROP FUNCTION IF EXISTS assistant.conv_tombstone();
DROP TABLE IF EXISTS assistant.conv_tombstones;
DROP TRIGGER IF EXISTS trg_conv_change_seq ON assistant.conversations;
DROP FUNCTION IF EXISTS assistant.bump_conv_change_seq();
ALTER TABLE assistant.conversations DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS assistant.conv_change_seq;
