DROP TRIGGER IF EXISTS trg_agent_tombstone ON jarvis.agents;
DROP FUNCTION IF EXISTS jarvis.agent_tombstone();
DROP TABLE IF EXISTS jarvis.agent_tombstones;
DROP TRIGGER IF EXISTS trg_agent_change_seq ON jarvis.agents;
DROP FUNCTION IF EXISTS jarvis.bump_agent_change_seq();
ALTER TABLE jarvis.agents DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS jarvis.agent_change_seq;
DROP TRIGGER IF EXISTS trg_folder_tombstone ON jarvis.folders;
DROP FUNCTION IF EXISTS jarvis.folder_tombstone();
DROP TABLE IF EXISTS jarvis.folder_tombstones;
DROP TRIGGER IF EXISTS trg_folder_change_seq ON jarvis.folders;
DROP FUNCTION IF EXISTS jarvis.bump_folder_change_seq();
ALTER TABLE jarvis.folders DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS jarvis.folder_change_seq;
DROP TRIGGER IF EXISTS trg_msg_bump_conv ON jarvis.messages;
DROP FUNCTION IF EXISTS jarvis.msg_bump_conv();
DROP TRIGGER IF EXISTS trg_conv_tombstone ON jarvis.conversations;
DROP FUNCTION IF EXISTS jarvis.conv_tombstone();
DROP TABLE IF EXISTS jarvis.conv_tombstones;
DROP TRIGGER IF EXISTS trg_conv_change_seq ON jarvis.conversations;
DROP FUNCTION IF EXISTS jarvis.bump_conv_change_seq();
ALTER TABLE jarvis.conversations DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS jarvis.conv_change_seq;
